### ISSUE TITLE
es_deployment : Surface metadata tags in deploymentdatasource

### ISSUE THREAD

**Issue by neiljbrookes** [elastic/terraform-provider-ec#243] opened 2021-02-17 10:20 UTC
## Overview

Tags are available as an argument for `ec_deployment` resource.
We should surface these tags in the equivalent `ec_deployment` data source.

**Comment by marclop** [comment] 2021-02-18 06:02
This is a duplicate of #182

**Closed by marclop** 2021-02-18 06:02 UTC
Labels: Team:Delivery, enhancement
