### ISSUE TITLE
Using "storage" in size_resource is not honoured 

### ISSUE THREAD

**Issue by beachfires** [elastic/terraform-provider-ec#568] opened 2022-12-08 15:14 UTC
## Readiness Checklist

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

the size specified for a particular topology should be for the storage aspect of the configuration when using `size_resource = "storage"`

## Current Behavior

I simply run this using `terraform apply` and the results are seen in the screenshot I've attached. As you can see, the storage sizes are definitely not the same as the ones defined in the terraform configuration file.
![Screenshot 2022-12-08 at 15 10 59](https://user-images.githubusercontent.com/72743072/206482664-4833e207-959b-4ddb-b84d-c32b9abfeda5.png)

## Terraform definition

```
data "ec_stack" "latest" {
  version_regex = "latest"
  region        = "aws-us-east-2"
}

resource "ec_deployment" "test" {
  name                   = "Test Terraform Deployment"
  region                 = "aws-us-east-2"
  version                = data.ec_stack.latest.version
  deployment_template_id = "aws-general-purpose-arm"

  elasticsearch {
    topology {
      id            = "cold"
      size          = "380g"
      size_resource = "storage"
      zone_count    = 1
    }

    topology {
      id            = "hot_content"
      size          = "60g"
      size_resource = "storage"
      zone_count    = 2
    }

    topology {
      id            = "ml"
      size          = "1g"
      size_resource = "memory"
      zone_count    = 1
    }
  }

  kibana {
    topology {
      zone_count    = 1
      size          = "1g"
      size_resource = "memory"
    }
  }

  integrations_server {
    topology {
      zone_count = 1
      size       = "1g"
    }
  }
}
```

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: elastic/ec 0.5.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS 8.5.2
* Environment name and version (e.g. Go 1.9):
* Server type and version:
* Operating System and version: MacOs 13.0.1
* Link to your project:

**Comment by eloo** [comment] 2023-02-14 14:16
we see something similar when updating the deployment_template_id

the plan looks like this

```
  # ec_deployment.elasticcloud_cluster will be updated in-place
  ~ resource "ec_deployment" "elasticcloud_cluster" {
      ~ deployment_template_id = "aws-io-optimized-v2" -> "aws-io-optimized-v3"
        id                     = "xxxxxxx"
        name                   = "aws-eu-central-1-emea-prod"
        tags                   = {}
        # (6 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
 ```

but its is actual downscaling our cluster to two zones (configured is 3) 

you can see also that the change in elasticsearch is not matching the terraform changes
![image](https://user-images.githubusercontent.com/2631895/218764090-31393785-800f-4e77-98c5-5e24abbf40ac.png)


this is really a big problem!

**Comment by eloo** [comment] 2023-02-14 14:59
looks like this will be fixed in 0.6.0 (locally tested)

can this fix be release in time? this is really a blocker right now

**Comment by tobio** [comment] 2023-02-15 05:39
@eloo I've just released a 0.5.1 version which includes the fix for this when changing deployment templates.

**Comment by eloo** [comment] 2023-02-15 08:07
@tobio awesome...
thanks for this quick release!

**Comment by tobio** [comment] 2023-05-12 04:47
I can't reproduce this behaviour in 0.6

**Closed by tobio** 2023-05-12 04:47 UTC
Labels: bug
