### ISSUE TITLE
[Bug] No support for darwin_arm64.

### ISSUE THREAD

**Issue by ndemeshchenko** [elastic/terraform-provider-ec#438] opened 2022-02-09 10:17 UTC
**Describe the bug**
```
Error: Incompatible provider version
Provider registry.terraform.io/elastic/ec v0.3.0 does not have a package available for your current platform, darwin_arm64.
```

**Desktop (please complete the following information):**
arch: darwin_arm64.

**Comment by jbielick** [comment] 2022-02-10 17:38
#414 has info

**Comment by tobio** [comment] 2022-04-19 20:11
Duplicate of https://github.com/elastic/terraform-provider-ec/issues/414

**Closed by tobio** 2022-04-19 20:11 UTC
