### ISSUE TITLE
Is it possible to enable self-monitoring with ec terraform provider?

### ISSUE THREAD

**Issue by abbanabennanih** [elastic/terraform-provider-ec#339] opened 2021-07-25 08:17 UTC
Hi,

Does elastic cloud terraform provider allow to enable self-monitoring? It seems not possible based on the following error:

> │ Error: Self-referential block
│
│ on deployment.tf line 50, in resource "ec_deployment" "cluster":
│ 50: deployment_id = ec_deployment.cluster.id
│
│ Configuration for ec_deployment.cluster may not refer to itself.

Terraform code:

observability {
deployment_id = ec_deployment.cluster.id
logs = false
metrics = true
}
...

Thank you,

Rgards

**Comment by marclop** [comment] 2021-07-26 08:17
@abbanabennanih thanks for opening the issue, this is however a duplicate of a question that has already been asked (see https://github.com/elastic/terraform-provider-ec/issues/333).

I'm closing this one off since all the answers you're looking for are in that issue.

**Closed by marclop** 2021-07-26 08:17 UTC
Labels: Team:Delivery, duplicate, question
