### ISSUE TITLE
Not visible in azure portal

### ISSUE THREAD

**Issue by brecht-vermeersch** [elastic/terraform-provider-ec#728] opened 2023-10-25 13:26 UTC
After creation I can't find it in the azure portal

**Comment by fwiedmann** [comment] 2023-12-29 08:54
hey @brecht-vermeersch,

I'm not from elastic, but I guess I can give you the answer:

You'll never see any resources of your elastic cloud deployments in you Azure Account.
With the cloud provider selection during the elastic deployment creation, you specify on which cloud provider the deployment should run.
From there, all the resources will be placed and managed in the cloud provider accounts of elastic.
You'll never see the actual resources, thats how SaaS work :)

**Comment by mrsymlove** [comment] 2024-01-18 17:13
is there no possibility to integrate ec_deployment https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/deployment with azurerm_elastic_cloud_elasticsearchhttps://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/elastic_cloud_elasticsearch
?

**Comment by Kushmaro** [comment] 2024-02-13 08:47
@brecht-vermeersch this is not an issue with the provider, rather relates to how the integration with Elastic/Azure works.
@fwiedmann your answer isn't quite accurate - you are generally correct, however, for Azure Marketplace customers, there's  an Elastic <> Azure integration that enables Azure MP customers to create resources directly from Azure portal. (in Elastic Cloud) 

@mrsymlove work related to the two provider resources won't solve this issue, this issue's root cause is more in the backend.

closing this, due to the above.

**Closed by Kushmaro** 2024-02-13 08:47 UTC
Labels: bug

**Comment by fwiedmann** [comment] 2024-02-13 08:51
@Kushmaro thanks for the hint. Is there any documentation for this MP <> EC integration?

**Comment by Kushmaro** [comment] 2024-02-13 08:56
maybe this will be helpful @fwiedmann 
https://www.elastic.co/guide/en/cloud/current/ec-azure-marketplace-native.html
