### ISSUE TITLE
Update ec_deployment data resource to lookup deployment by name/alias

### ISSUE THREAD

**Issue by emoshaya** [elastic/terraform-provider-ec#638] opened 2023-05-06 12:47 UTC
## Overview
Update ec_deployment data resource to lookup deployment by name/alias

## Possible Implementation
```
data "ec_deployment" "example" {
    name = "deployment"
}
```

**Comment by gigerdo** [comment] 2024-04-04 09:41
Closing it because I think this is a duplicate of https://github.com/elastic/terraform-provider-ec/issues/639

**Closed by gigerdo** 2024-04-04 09:41 UTC
Labels: enhancement
