### ISSUE TITLE
Terraform apply fails with: Error: failed to obtain a stack version matching "7.16.0" 

### ISSUE THREAD

**Issue by aalonso-solusoft** [elastic/terraform-provider-ec#449] opened 2022-03-01 07:56 UTC
## Readiness Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
Terraform apply should work.

## Current Behavior
Terraform apply is failing with the following error: "failed to obtain a stack version matching "7.17.0": please specify a valid version_regex".

## Terraform Definition 
  
```terraform
provider "ec" {

}

data "ec_stack" "latest" {
  version_regex = "7.17.0"
  region        = "azure-westeurope"
}

resource "ec_deployment" "ta" {
  name = local.bbdd_name

  region                 = data.ec_stack.latest.region
  version                = data.ec_stack.latest.version_regex
  deployment_template_id = "azure-io-optimized"

  elasticsearch {
    topology {
      id = "hot_content"
      size = "1g"
      zone_count = 1
    }
  }

  kibana {}
}
```

## Steps to Reproduce  

1. terraform init.
2. terraform plan.
3. terraform apply.

## Your Environment

- Version used: Provider: 0.3.0, Stack version: 7.17.0
- Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS
- Environment name and version (e.g. Go 1.9):
- Server type and version:
- Operating System and version: windows 10 as well as alpine 3.13 (CI/CD)
- Link to your project:

**Comment by tobio** [comment] 2022-03-01 23:32
@aalonso-solusoft this behaviour is caused by a strict implementation of the Elasticsearch Service [version policy](https://www.elastic.co/guide/en/cloud/current/ec-version-policy.html). 

I'm raising the impact this has on Terraform provider users. Ideally the list of available versions should include the versions used by running deployments in an account, which would fix the issue you're seeing here. 

I don't have a timeline for when this will be fixed, but we're aware of the issue.

**Comment by aalonso-solusoft** [comment] 2022-03-04 12:23
Ok @tobio, yes, that would be a nice fix. We are following the issue state. 

Thank you very much.

**Comment by robertlindner** [comment] 2022-09-02 09:52
Can we expect progress on this anytime soon?

I have a slightly related problem:
Recently elastic stack 8.4 released.
I have a deployment still running on 8.3.3, with a version constraint of 8.3.? defined in terraform. I now needed to work on a unrelated Google Cloud Function that is defined in the same Terraform root module, and the EC provider fails with:

```
╷
│ Error: failed to obtain a stack version matching "8.3.?": please specify a valid version_regex
│ 
│   with module.ec_stack.module.ec_deployment_main["<redacted>"].data.ec_stack.version,
│   on .terraform/modules/ec_stack.ec_deployment_main/main.tf line 1, in data "ec_stack" "version":
│    1: data "ec_stack" "version" {
│ 
╵

```

According to https://www.elastic.co/guide/en/cloud/current/ec-version-policy.html#ec-version-policy-available version 8.3.3 should still be available?
> We make the two latest minor versions of the latest major version available for provisioning.

Best regards, 
Robert

**Comment by tobio** [comment] 2022-09-04 23:37
@robertlindner the Cloud API behaviour here is being changed to include any Stack versions in use by a specific account. Looking at the release schedule it should be available within the next 6 weeks, but it's not yet merged so that date isn't fixed.

> with a version constraint of 8.3.? defined in terraform

It looks like your regex isn't quite correct here, this would only match `8.3` optionally followed by any character. You probably want something like `8\.3\..+`

For example:

```hcl
data "ec_stack" "eight-three" {
  version_regex = "8\\.3\\..+"
  region        = "aws-eu-west-2"
} 
```

**Comment by robertlindner** [comment] 2022-09-05 06:58
As I understand it the version_regex should be correct, at least it works for `8.4.?` and `7.17.?`
Also the [docs](https://registry.terraform.io/providers/elastic/ec/latest/docs/data-sources/ec_stack) show the expression I use

I can't make it work with any regex for 8.3.3, all of the following give the same error:
```
"8\\.3\\..+"
"8.3.?"
"8.3.3"
"8\\.3\\.3"
```

From what I understand the Cloud API behavior is that it just returns the latest 8.x and latest 7.x at the Moment?

**Comment by Kushmaro** [comment] 2024-02-13 08:28
closing this one, as more versions are now available via the API, and this hadn't been a provider issue to begin with.

**Closed by Kushmaro** 2024-02-13 08:28 UTC
Labels: bug
