### ISSUE TITLE
AAD Connection During Cluster Creation fails

### ISSUE THREAD

**Issue by 4dminasecuretti** [elastic/terraform-provider-ec#392] opened 2021-10-14 10:11 UTC
We are trying to create an ec_deployment with a Azure AD connection in the config part.
## Readiness Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
A healthy ec_deployment with following oicd configuration in the user settings of elasticsearch:
```yaml
xpack:
  security:
    authc:
      realms:
        oidc:
          _oidc1_name_:
            order: 2
            rp.client_id: "<Application (client) ID>"
            rp.response_type: "code"
            rp.requested_scopes: ["openid", "email"]
            rp.redirect_uri: "KIBANA_ENDPOINT_URL/api/security/oidc/callback"
            op.issuer: "https://login.microsoftonline.com/<Directory (tenant) ID>/v2.0"
            op.authorization_endpoint: "https://login.microsoftonline.com/<Directory (tenant) ID>/oauth2/v2.0/authorize"
            op.token_endpoint: "https://login.microsoftonline.com/<Directory (tenant) ID>/oauth2/v2.0/token"
            op.userinfo_endpoint: "https://graph.microsoft.com/oidc/userinfo"
            op.endsession_endpoint: "https://login.microsoftonline.com/<Directory (tenant) ID>/oauth2/v2.0/logout"
            rp.post_logout_redirect_uri: "KIBANA_ENDPOINT_URL/logged_out"
            op.jwkset_path: "https://login.microsoftonline.com/<Directory (tenant) ID>/discovery/v2.0/keys"
            claims.principal: name
            claims.groups: groups

```
and kibana:
```yaml
xpack.security.authc.providers:
  oidc._oidc1_name_:
    order: 0
    realm: _oidc1_name_
    description: "Log in with Azure"
  basic.basic1:
    order: 1
```

https://www.elastic.co/guide/en/cloud/current/ec-securing-clusters-oidc-op.html

## Current Behavior
After a successful terraform plan the apply fails during the creation of the ec_deployment with following errors:
```
Error: failed tracking create progress: 3 errors occurred:
│ 	* found deployment plan errors: deployment [_deployment-id_] - [elasticsearch][_elastic-endpoint-id_]: caught error: "Plan change failed: Some instances were not running"
│ 	* found deployment plan errors: deployment [_deployment-id_] - [kibana][_kibana-endpoint-id_]: caught error: "Plan change failed: Cluster not reachable: [elasticsearch]... Please validate the cluster is in a healthy state and retry."
│ 	* set "request_id" to "_request-id_" to recreate the deployment resources
```

The result is an unhealthy ec_deployment.

Neither a "new run", a "rerun failed jobs" nor a new run with the request-id fix this issue.
Instead, a second unhealthy cluster is created in each case.

## Terraform definition
```
ec = {
      source = "elastic/ec"
      version = "0.2.1"
    }
```

## Steps to Reproduce
1. create a cluster like following:
![image](https://user-images.githubusercontent.com/92514273/137295502-afad6808-8f5b-4302-befa-9f6c2e0e59ff.png)

2. execute terraform apply

## Context
We want to create a healthy cluster with an aad connection in one step.

## Possible Solution
Create the cluster without the config part via TF in a first step (Azure Pipeline).
Use a second step with the config part and the cluster gets modified correctly.

## Your Environment
* Version used: 0.2.1
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version:
* Environment name and version (e.g. Go 1.9):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by rogerioefonseca** [comment] 2022-05-24 09:36
Hello there, do we have updates here?
We are facing the same issue and I would like to know what is the current plan to this open issue.
Best,

**Comment by 4dminasecuretti** [comment] 2022-05-24 11:47
Hi @rogerioefonseca,
our last update was on 03.11.21:
"Currently, there is no quick fix for the situation available. The developers took your open issue (https://github.com/elastic/terraform-provider-ec/issues/392) and pinned that to their rough plan for the next release.
This might not work out, and it gets shifted, but this is now on the product roadmap. You can track this on the open public issue."

**Comment by tobio** [comment] 2022-05-25 10:11
Duplicate of https://github.com/elastic/terraform-provider-ec/issues/433

**Closed by tobio** 2022-05-25 10:11 UTC
Labels: bug
