### ISSUE TITLE
"Value of field 'elasticsearch.version' cannot be changed" when creating new deployment

### ISSUE THREAD

**Issue by linefeedse** [elastic/terraform-provider-ec#256] opened 2021-03-10 17:15 UTC
Unsure if this is a bug or a general question, as it seems rather strange that this basic functionality wouldn't work. Apologies if there's an obvious step I missed.

Using terraform 0.14.7 and ec provider version v0.1.0-beta, I can not create a new deployment as per the docs in https://github.com/elastic/terraform-provider-ec/blob/master/docs/resources/ec_deployment.md

When trying, i get the error message:
```
Error: failed creating deployment: 2 errors occurred:
        * api error: clusters.cluster_plan_change_prohibited: The requested cluster configuration change is not permitted. Value of field 'elasticsearch.version' cannot be changed to [7.9.2]. (resources.elasticsearch[0].elasticsearch.version)
        * set "request_id" to "9sa1pv9xsnqugs7qo3rd62nyz87byja4gkxebw5k8q6hm771yu938ear8di5ykfr" to recreate the deployment resources
```
[request.log](https://github.com/elastic/terraform-provider-ec/files/6117670/request.log)

## Expected Behavior
Im expecting a deployment to be created
## Current Behavior
Error: failed creating deployment: 2 errors occurred:
        * api error: clusters.cluster_plan_change_prohibited: The requested cluster configuration change is not permitted. Value of field 'elasticsearch.version' cannot be changed to [7.9.2]. (resources.elasticsearch[0].elasticsearch.version)
        * set "request_id" to "9sa1pv9xsnqugs7qo3rd62nyz87byja4gkxebw5k8q6hm771yu938ear8di5ykfr" to recreate the deployment resources

## Terraform definition
resource "ec_deployment" "example_minimal" {
  name = "my_example_deployment"
  region                 = "us-east-1"
  version                = "7.9.2"
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {}

  kibana {}

  apm {}

  enterprise_search {}
}

## Steps to Reproduce
1. Get an API key
2. Create terraform code for provider and resource as per the docs
3. terraform apply

## Context
I am trying to create a second ec deployment using terraform, we have one previous deployment in our account, that was created through the EC portal.

## Your Environment
* Version used: terraform 0.14.7
* Operating System and version: Fedora Linux 33

**Comment by karencfv** [comment] 2021-03-11 01:47
Thanks for opening this issue @linefeedse :)

I created a deployment with the values you specified and the deployment was created successfully.

```console
$ terraform version
Terraform v0.14.7

$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding elastic/ec versions matching "0.1.0-beta"...
- Installing elastic/ec v0.1.0-beta...
- Installed elastic/ec v0.1.0-beta (unauthenticated)

<...>

Terraform has been successfully initialized!
<...>
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ec_deployment.example_minimal will be created
  + resource "ec_deployment" "example_minimal" {
      + apm_secret_token       = (sensitive value)
      + deployment_template_id = "aws-io-optimized-v2"
      + elasticsearch_password = (sensitive value)
      + elasticsearch_username = (known after apply)
      + id                     = (known after apply)
      + name                   = "my_example_deployment"
      + region                 = "us-east-1"
      + version                = "7.9.2"

      + apm {
          + elasticsearch_cluster_ref_id = "main-elasticsearch"
          + http_endpoint                = (known after apply)
          + https_endpoint               = (known after apply)
          + ref_id                       = "main-apm"
          + region                       = (known after apply)
          + resource_id                  = (known after apply)
          + version                      = (known after apply)

          + topology {
              + instance_configuration_id = (known after apply)
              + size                      = (known after apply)
              + size_resource             = (known after apply)
              + zone_count                = (known after apply)
            }
        }

      + elasticsearch {
          + cloud_id       = (known after apply)
          + http_endpoint  = (known after apply)
          + https_endpoint = (known after apply)
          + ref_id         = "main-elasticsearch"
          + region         = (known after apply)
          + resource_id    = (known after apply)
          + version        = (known after apply)

          + topology {
              + instance_configuration_id = (known after apply)
              + node_type_data            = (known after apply)
              + node_type_ingest          = (known after apply)
              + node_type_master          = (known after apply)
              + node_type_ml              = (known after apply)
              + size                      = (known after apply)
              + size_resource             = (known after apply)
              + zone_count                = (known after apply)
            }
        }

      + enterprise_search {
          + elasticsearch_cluster_ref_id = "main-elasticsearch"
          + http_endpoint                = (known after apply)
          + https_endpoint               = (known after apply)
          + ref_id                       = "main-enterprise_search"
          + region                       = (known after apply)
          + resource_id                  = (known after apply)
          + version                      = (known after apply)

          + topology {
              + instance_configuration_id = (known after apply)
              + node_type_appserver       = (known after apply)
              + node_type_connector       = (known after apply)
              + node_type_worker          = (known after apply)
              + size                      = (known after apply)
              + size_resource             = (known after apply)
              + zone_count                = (known after apply)
            }
        }

      + kibana {
          + elasticsearch_cluster_ref_id = "main-elasticsearch"
          + http_endpoint                = (known after apply)
          + https_endpoint               = (known after apply)
          + ref_id                       = "main-kibana"
          + region                       = (known after apply)
          + resource_id                  = (known after apply)
          + version                      = (known after apply)

          + topology {
              + instance_configuration_id = (known after apply)
              + size                      = (known after apply)
              + size_resource             = (known after apply)
              + zone_count                = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + deployment_id                = (known after apply)
  + elasticsearch_cloud_id       = (known after apply)
  + elasticsearch_https_endpoint = (known after apply)
  + elasticsearch_password       = (known after apply)
  + elasticsearch_username       = (known after apply)
  + elasticsearch_version        = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ec_deployment.example_minimal: Creating...
<...>
ec_deployment.example_minimal: Creation complete after 5m41s [id=<deployment-id>]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Did you import your other deployment into the same directory by any chance? Terraform might be trying to apply a change rather than creating a new resource.

**Comment by linefeedse** [comment] 2021-03-11 07:40
No imports, empty state.
Started out with an empty directory, only this terraform code in a file:
```
terraform {
  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "0.1.0-beta"
    }
  }
}

provider "ec" {
  verbose = true
}

resource "ec_deployment" "example_minimal" {
  name = "my_example_deployment"
  region                 = "us-east-1"
  version                = "7.9.2"
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {}
  kibana {}
  apm {}
  enterprise_search {}
}
```
Then I run it exactly like this:
```
$ terraform init
Initializing the backend...

Initializing provider plugins...
- Reusing previous version of elastic/ec from the dependency lock file
- Using previously-installed elastic/ec v0.1.0-beta

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ec_deployment.example_minimal will be created
  + resource "ec_deployment" "example_minimal" {
      + apm_secret_token       = (sensitive value)
      + deployment_template_id = "aws-io-optimized-v2"
      + elasticsearch_password = (sensitive value)
      + elasticsearch_username = (known after apply)
      + id                     = (known after apply)
      + name                   = "my_example_deployment"
      + region                 = "us-east-1"
      + version                = "7.9.2"

      + apm {
          + elasticsearch_cluster_ref_id = "main-elasticsearch"
          + http_endpoint                = (known after apply)
          + https_endpoint               = (known after apply)
          + ref_id                       = "main-apm"
          + region                       = (known after apply)
          + resource_id                  = (known after apply)
          + version                      = (known after apply)

          + topology {
              + instance_configuration_id = (known after apply)
              + size                      = (known after apply)
              + size_resource             = (known after apply)
              + zone_count                = (known after apply)
            }
        }

      + elasticsearch {
          + cloud_id       = (known after apply)
          + http_endpoint  = (known after apply)
          + https_endpoint = (known after apply)
          + ref_id         = "main-elasticsearch"
          + region         = (known after apply)
          + resource_id    = (known after apply)
          + version        = (known after apply)

          + topology {
              + instance_configuration_id = (known after apply)
              + node_type_data            = (known after apply)
              + node_type_ingest          = (known after apply)
              + node_type_master          = (known after apply)
              + node_type_ml              = (known after apply)
              + size                      = (known after apply)
              + size_resource             = (known after apply)
              + zone_count                = (known after apply)
            }
        }

      + enterprise_search {
          + elasticsearch_cluster_ref_id = "main-elasticsearch"
          + http_endpoint                = (known after apply)
          + https_endpoint               = (known after apply)
          + ref_id                       = "main-enterprise_search"
          + region                       = (known after apply)
          + resource_id                  = (known after apply)
          + version                      = (known after apply)

          + topology {
              + instance_configuration_id = (known after apply)
              + node_type_appserver       = (known after apply)
              + node_type_connector       = (known after apply)
              + node_type_worker          = (known after apply)
              + size                      = (known after apply)
              + size_resource             = (known after apply)
              + zone_count                = (known after apply)
            }
        }

      + kibana {
          + elasticsearch_cluster_ref_id = "main-elasticsearch"
          + http_endpoint                = (known after apply)
          + https_endpoint               = (known after apply)
          + ref_id                       = "main-kibana"
          + region                       = (known after apply)
          + resource_id                  = (known after apply)
          + version                      = (known after apply)

          + topology {
              + instance_configuration_id = (known after apply)
              + size                      = (known after apply)
              + size_resource             = (known after apply)
              + zone_count                = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ec_deployment.example_minimal: Creating...

Error: failed creating deployment: 2 errors occurred:
        * api error: clusters.cluster_plan_change_prohibited: The requested cluster configuration change is not permitted. Value of field 'elasticsearch.version' cannot be changed to [7.9.2]. (resources.elasticsearch[0].elasticsearch.version)
        * set "request_id" to "kmtayvyk8wu44ktt7dk3fmswau2itrpzod1vlhslk0ozlkpqdps3jtsey6o9vkp0" to recreate the deployment resources



  on elasticsearch.tf line 1, in resource "ec_deployment" "example_minimal":
   1: resource "ec_deployment" "example_minimal" {

$
```

**Comment by guitmz** [comment] 2021-03-15 10:56
Confirmed the issue on my end too. Our scenario:

1. create a deployment using terraform provider in statefile A
2. try to create a deployment (different name) in statefile B
3. error is displayed like above

**Comment by karencfv** [comment] 2021-03-15 22:09
@linefeedse Thanks for your patience :) Unfortunately I have not been able to reproduce your error. Could you try out the following and tell me your results?

- In a new directory with an empty state change the name of the resource (`resource "ec_deployment" "example_minimal_test" {`) and run a terraform apply?
- Build the provider from source by following these [these instructions](https://github.com/elastic/terraform-provider-ec/blob/master/CONTRIBUTING.md#build-terraform-provider-ec-locally-with-your-changes), and in a new directory with an empty state run a terraform apply.

**Comment by karencfv** [comment] 2021-03-15 22:11
Hi @guitmz, could you show me the contents of your configuration files?

**Comment by marclop** [comment] 2021-03-16 11:15
Hi all, apologies for the late reply.

The main issue here is that our examples are somewhat outdated and aren't using the latest version. Version `7.9.x` cannot be used anymore since it's not within the latests two feature releases (`7.11.x` and `7.10.x`), [we keep a policy in ESS](https://www.elastic.co/guide/en/cloud/current/ec-version-policy.html#ec-version-policy-available) where we only allow deployments to be created with the latest feature version or -1.

We will update the documentation and examples accordingly to make sure this doesn't happen again and make sure to document this case as well in the documentation.

**Comment by guitmz** [comment] 2021-03-16 11:25
@karencfv I will share them when I can

@marclop I'm using 7.11 and I'm having the same issue.

**Comment by marclop** [comment] 2021-03-16 11:33
@guitmz which version of the `7.11` stack are you using in your terraform configuration? Only `7.11.2` can be used right now in that feature version.

**Comment by guitmz** [comment] 2021-03-16 13:28
@marclop ah, I see! that's correct, I changed to 7.11.2 for the new cluster I'm creating and it works now. Existing cluster can stay at 7.11.1

I then suggest the error message to be changed to something more meaningful like "version not supported anymore, chose from [x, y, z]" or something like this.

**Comment by marclop** [comment] 2021-03-17 09:26
This error comes from our API, I will relay the feedback back to the relevant team to have a more actionable error message.

**Comment by Kushmaro** [comment] 2021-03-17 17:49
@marclop how do you feel about a "latest" value for the version field? 
Technically this needs to be fetched from listing stackpacks I guess though

**Comment by karencfv** [comment] 2021-03-17 21:31
@Kushmaro We have a PR open for this :) https://github.com/elastic/terraform-provider-ec/pull/261

**Comment by marclop** [comment] 2021-03-24 04:42
There's no actionable items left to be done done here, I'll close this issue but pin it in the issues page so other users that stumble on this can find this issue easily.

**Closed by marclop** 2021-03-24 04:42 UTC
Labels: Team:Delivery, question

**Comment by guibirow** [comment] 2021-07-21 10:39
I think the provider should output a user friendly message and say that the version is not supported anymore instead of giving a generic error, this is misleading and force us to look after many possible issues before finding this issue.

**Comment by marclop** [comment] 2021-07-26 08:15
@guibirow The API error has been updated in the relevant services and the change will be available in the Elasticsearch Service fairly soon, there isn't a need to tweak the provider to make the error more readable since the problem has been addressed at the source.
